AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Voice Lexicon API

Parameters:
  BUCKETNAME:
    Type: String
    Description: S3 Bucket name where will be recordings uploaded
    MinLength: 4
    MaxLength: 50


Resources:
  HandleFormLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      FunctionName: HandleFormLambda
      Runtime: python3.6
      CodeUri: ./HandleForm
      Description: ''
      MemorySize: 128
      Timeout: 60
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BUCKETNAME
      Environment:
        Variables:
          BucketName: !Ref BUCKETNAME
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /HandleForm
            Method: ANY

  GenSoundLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      FunctionName: GenSoundLambda
      Runtime: python3.6
      CodeUri: ./GenSound
      Description: ''
      MemorySize: 128
      Timeout: 60
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BUCKETNAME
      Environment:
        Variables:
          BucketName: !Ref BUCKETNAME
