AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Voice Lexicon API

Parameters:
  BUCKETNAME:
    Type: String
    Description: S3 Bucket name where will be recordings uploaded
    MinLength: 4
    MaxLength: 50

Resources:
  LambdaGenSound:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./HandleForm
      Description: 'Lambda function handling requests from the HTML form'
      MemorySize: 128
      Timeout: 300
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BUCKETNAME
      Environment:
        Variables:
          BucketName: !Ref BUCKETNAME
